# Generated by Django 2.1.1 on 2018-09-22 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='on_off',
            old_name='choice',
            new_name='On_Off_text',
        ),
        migrations.RenameField(
            model_name='temperature',
            old_name='question',
            new_name='temp_text',
        ),
    ]
