# Generated by Django 2.1.1 on 2018-09-22 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20180922_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mytable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('tmp', models.CharField(max_length=10)),
                ('stat', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='on_off',
            name='temperature',
        ),
        migrations.DeleteModel(
            name='On_Off',
        ),
        migrations.DeleteModel(
            name='Temperature',
        ),
    ]
